Create SignUp UI at SharedUI
AmruTheSeeker/Eventmaker pull request #7
Opened 2023-09-18 13:40 UTC by AmruTheSeeker

Your review and comment please. Thank you

2023-09-19 02:15 UTC, indrazm commented on src/app/page.js
Please clean up, the Code you don't need. 
In production we accept commented line, but this one, doesn't look good. :)

2023-09-19 02:25 UTC, indrazm commented on src/components/SharedUI/SignUp.jsx
This one is bad for readibility. You can change the structure with rebuild an Input Component that consist label and input as children. And expose all the dynamic value as props. For example : 

File : Input.jsx

```jsx
export const Input = ({ label, type, name,  placeholder, onChange}) => {
  return (
    <div>
      <label htmlFor="name" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
        {label}
      </label>
      <input
        type={type}
        name={name}
        className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
        placeholder={placeholder}
        onChange={onChange}
        required
      />
    </div>
  );
};
```

# Please re-check. 

In React you should use className instead of class.

And do not use any anchor tag. 

```html
<a href="....">link</a> 👎 
<Link href="...">link</a> 👍 
```

2023-09-19 02:26 UTC, indrazm requested changes
Hey, I've made comments and please change.

2023-09-19 05:55 UTC, AmruTheSeeker commented on src/app/page.js
I cleaned unused line code accordingly. 
Recently i used page.js to render my card.jsx. My full code at page.js will shown like below. 

Does this acceptable? I still keep this code line at my local, haven't push to GitHub.

//import { AuthRegister } from "@/components/Auth/Auth.Register";
//import { Button } from "@/components/SharedUI/Button";
//import { SignUp } from "@/components/SharedUI/SignUp"
import {Card} from "@/components/SharedUI/Card"

export default function Page() {
  return <Card/>
  //return <SignUp/>;
  //return <Button/>;
  

}

2023-09-19 05:58 UTC, AmruTheSeeker commented
> Hey, I've made comments and please change.

Ok, i'll do my best

2023-09-19 08:17 UTC, indrazm commented on src/app/page.js
You should commit first, not write here. :)

2023-09-20 03:46 UTC, indrazm commented on src/components/LandingPage/components/LandingPage.Header.jsx
Again, please recheck every line. i still see class instead of className at input tag. 😆

2023-09-20 03:47 UTC, indrazm commented on src/styles/globals.css
.card should not in @layer base
it should inside @layer components

2023-09-21 01:27 UTC, AmruTheSeeker commented
Pull Request :
1. Synchonize existing folder and file structure, with teached at zoom record day-19 as reference.
2. Revise authorityUI and create it functionality.
3. Fix UI at landingpage for event search button problem at my branch.
4. Create and focus in Authority folder, Api Test folder and Middleware.js for authority functionality.
5. Create README.md file

Others :
1. Update wiki at GitHub.
2. Install library next UI framer-motion.
3. Install library flowbite-react. (but haven't use it yet).
4. Install library jose.
5. Install library js-cookie.

Next plan :
- Focus in helping event landing page and other supporting page; and create it's functionality.

2023-09-21 03:11 UTC, indrazm commented on src/components/Auth/components/Register.jsx
Clean up the className

2023-09-21 03:12 UTC, indrazm commented on src/components/SharedUI/Card.jsx
`import Image from "next/image"

<Image src="/MobileLegend.jpg" alt="Mobile Legend" width={400} height={400} />

2023-09-21 03:13 UTC, indrazm requested changes
Good!

2023-09-22 13:19 UTC, merged